services:

    gendoria_command_queue.processor_factory:
        class: Gendoria\CommandQueueBundle\CommandQueue\ContainerAwareProcessorFactory
        arguments: 
            - '@service_container'
            - '@?logger'
            
    gendoria_command_queue.manager:
        class: Gendoria\CommandQueue\QueueManager\MultipleQueueManager
        arguments:
            - '@?logger'
            
    gendoria_command_queue.driver.direct:
        class: Gendoria\CommandQueue\SendDriver\DirectProcessingDriver
        calls:
            - [setLogger, ['@?logger']]
