services:

    gendoria_command_queue.processor_factory:
        class: Gendoria\CommandQueueBundle\ProcessorFactory\ContainerAwareProcessorFactory
        arguments: 
            - '@service_container'
            - '@?logger'
            
    gendoria_command_queue.manager:
        class: Gendoria\CommandQueue\QueueManager\MultipleQueueManager
        arguments:
            - '@?logger'
            
    gendoria_command_queue.runner_manager:
        class: Gendoria\CommandQueueBundle\Worker\WorkerRunnerManager
        arguments:
            - '@service_container'
            
    gendoria_command_queue.driver.direct:
        class: Gendoria\CommandQueue\SendDriver\DirectProcessingDriver
        arguments:
            - '@gendoria_command_queue.processor_factory'
            - '@?logger'
        calls:
            - [setLogger, ['@?logger']]
            
    gendoria_command_queue.command.list:
        class: Gendoria\CommandQueue\Console\Command\ListWorkersCommand
        calls:
            - [setRunnerManager, ['@gendoria_command_queue.runner_manager']]
        tags:
            - { name: console.command }            
            
    gendoria_command_queue.command.run:
        class: Gendoria\CommandQueue\Console\Command\RunWorkerCommand
        calls:
            - [setRunnerManager, ['@gendoria_command_queue.runner_manager']]
        tags:
            - { name: console.command }            

    gendoria_command_queue.listener.clear_logs:
        class: Gendoria\CommandQueueBundle\Listener\ClearLogsListener
        arguments:
            - '@logger'
        tags:
            - { name: kernel.event_subscriber }
            
    gendoria_command_queue.listener.clear_entity_managers:
        class: Gendoria\CommandQueueBundle\Listener\ClearEntityManagersListener
        arguments:
            - '@doctrine'
        tags:
            - { name: kernel.event_subscriber }